[2024-09-20T20:48:34.929+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T20:48:34.939+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_paralela.segunda_task manual__2024-09-20T20:48:33.282289+00:00 [queued]>
[2024-09-20T20:48:34.944+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_paralela.segunda_task manual__2024-09-20T20:48:33.282289+00:00 [queued]>
[2024-09-20T20:48:34.944+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-20T20:48:34.952+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): segunda_task> on 2024-09-20 20:48:33.282289+00:00
[2024-09-20T20:48:34.956+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T20:48:34.957+0000] {standard_task_runner.py:72} INFO - Started process 157 to run task
[2024-09-20T20:48:34.957+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'task_paralela', 'segunda_task', 'manual__2024-09-20T20:48:33.282289+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/task_paralela.py', '--cfg-path', '/tmp/tmp0460s066']
[2024-09-20T20:48:34.958+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask segunda_task
[2024-09-20T20:48:34.983+0000] {task_command.py:467} INFO - Running <TaskInstance: task_paralela.segunda_task manual__2024-09-20T20:48:33.282289+00:00 [running]> on host 22a02bcf3677
[2024-09-20T20:48:35.031+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Everton Soares' AIRFLOW_CTX_DAG_ID='task_paralela' AIRFLOW_CTX_TASK_ID='segunda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T20:48:33.282289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T20:48:33.282289+00:00'
[2024-09-20T20:48:35.031+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T20:48:35.040+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-20T20:48:35.041+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Sou a segunda task, serei executada depois do sucesso da tarefa 1'"]
[2024-09-20T20:48:35.048+0000] {subprocess.py:86} INFO - Output:
[2024-09-20T20:48:35.049+0000] {subprocess.py:93} INFO - Sou a segunda task, serei executada depois do sucesso da tarefa 1
[2024-09-20T20:48:35.050+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-20T20:48:35.064+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T20:48:35.065+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=task_paralela, task_id=segunda_task, run_id=manual__2024-09-20T20:48:33.282289+00:00, execution_date=20240920T204833, start_date=20240920T204834, end_date=20240920T204835
[2024-09-20T20:48:35.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-20T20:48:35.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
