[2024-09-20T20:58:11.562+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T20:58:11.572+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_With_Python_Operator.ola_mundo manual__2024-09-20T20:58:10.664131+00:00 [queued]>
[2024-09-20T20:58:11.576+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_With_Python_Operator.ola_mundo manual__2024-09-20T20:58:10.664131+00:00 [queued]>
[2024-09-20T20:58:11.577+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-20T20:58:11.584+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): ola_mundo> on 2024-09-20 20:58:10.664131+00:00
[2024-09-20T20:58:11.589+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T20:58:11.590+0000] {standard_task_runner.py:72} INFO - Started process 308 to run task
[2024-09-20T20:58:11.591+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_With_Python_Operator', 'ola_mundo', 'manual__2024-09-20T20:58:10.664131+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_com_operador_python.py', '--cfg-path', '/tmp/tmpfb3399ka']
[2024-09-20T20:58:11.591+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask ola_mundo
[2024-09-20T20:58:11.617+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_With_Python_Operator.ola_mundo manual__2024-09-20T20:58:10.664131+00:00 [running]> on host 22a02bcf3677
[2024-09-20T20:58:11.661+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Everton Soares' AIRFLOW_CTX_DAG_ID='DAG_With_Python_Operator' AIRFLOW_CTX_TASK_ID='ola_mundo' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T20:58:10.664131+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T20:58:10.664131+00:00'
[2024-09-20T20:58:11.661+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T20:58:11.670+0000] {logging_mixin.py:190} INFO - Ol√°, Mundo!
[2024-09-20T20:58:11.670+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-20T20:58:11.677+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T20:58:11.677+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=DAG_With_Python_Operator, task_id=ola_mundo, run_id=manual__2024-09-20T20:58:10.664131+00:00, execution_date=20240920T205810, start_date=20240920T205811, end_date=20240920T205811
[2024-09-20T20:58:11.723+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-20T20:58:11.735+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T20:58:11.736+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
